spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Books
  main:
    allow-circular-references: true

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - my.spring.changelogs